# Generate tests/suite-prefix-bundle.lua: the official suite's prefix --
# every file tests/all.lua runs up to and including locals.lua -- bundled
# into ONE self-contained Lua script with no filesystem dependency (sources
# embedded; loadfile/dofile overridden to read them from memory).
#
#   cd <repo root> && python3 scripts/suite-bundle.py
#
# Why it exists: V8 12.x (Node 22) SIGSEGVs the HOST process at
# locals.lua's to-be-closed-in-coroutines tests, but only after executing
# the files before it -- the corruption is planted earlier and detonates
# there (doc/wasm-audit-2026-07-05.md, finding 1). Reproducing that needs
# the whole prefix to run in order, and engines without a filesystem (a
# browser tab; a V8 bug-report harness) can't loadfile. This bundle is the
# portable detonation witness:
#
#   native lua, wasmtime, Chromium 141 (V8 14.1): SUITE-PREFIX PASS
#   Node 22 --experimental-wasm-exnref (V8 12.4): host SIGSEGV (exit 139)
#
# Two deviations from all.lua, both required by bundling, neither able to
# mask a host crash:
#   - main.lua runs plain, not through all.lua's string.dump round-trip
#     (it is a no-op in port mode; the round-trip shifts gc.lua's tight
#     memory accounting under bundling).
#   - gc.lua's tightest tolerance (count <= m+1 KB) is widened to m+3:
#     holding the sources as chunk constants shifts absolute heap size by
#     ~1 KB, and that assert measures absolute memory, not behavior.
import sys

FILES = ["main.lua", "tracegc.lua", "gc.lua", "db.lua", "calls.lua",
         "strings.lua", "literals.lua", "tpack.lua", "attrib.lua",
         "gengc.lua", "locals.lua"]

def lua_quote(data: bytes) -> str:
    out = []
    for b in data:
        c = chr(b)
        if c == '"': out.append('\\"')
        elif c == '\\': out.append('\\\\')
        elif c == '\n': out.append('\\n')
        elif c == '\r': out.append('\\r')
        elif 32 <= b < 127: out.append(c)
        else: out.append('\\%03d' % b)
    return '"' + ''.join(out) + '"'

parts = ["-- GENERATED by scripts/suite-bundle.py -- do not edit",
         "_port = true", "local sources = {"]
for f in FILES:
    with open(f"tests/{f}", "rb") as fh:
        data = fh.read()
    if f == "gc.lua":
        # bundling deviation (see header): absolute-memory tolerance
        data = data.replace(b'assert(collectgarbage("count") <= m + 1)',
                            b'assert(collectgarbage("count") <= m + 3)')
    parts.append(f'  ["{f}"] = {lua_quote(data)},')
parts.append("}")
parts.append("""
local realload = load
local function myloadfile(n)
  local s = sources[n]
  if not s then return nil, "no embedded file: "..n end
  if s:sub(1,1) == "#" then s = "--" .. s:sub(2) end  -- shebang, as loadfile does
  return realload(s, "@"..n)
end
loadfile = myloadfile
dofile = function (n) return assert(myloadfile(n))() end
package.preload.tracegc = function() return assert(myloadfile("tracegc.lua"))() end

-- mimic of tests/all.lua's prefix machinery (its lines ~54-172), fs-free
print("\\n\\tStarting Tests (suite prefix bundle)")
do local x, y = math.randomseed() end
local initclock = os.clock()
local lastclock = initclock
local function showmem ()
  collectgarbage("count")
end
local function report (n) print("\\n***** FILE '"..n.."'*****") end
local ddofile = function (n, strip)   -- all.lua's dump/undump dofile
  showmem()
  local c = os.clock()
  print(string.format("time: %g (+%g)", c - initclock, c - lastclock))
  lastclock = c
  report(n)
  local f = assert(myloadfile(n))
  local b = string.dump(f, strip)
  f = assert(realload(b))
  return f()
end

dofile('main.lua')  -- bundling deviation (see header): plain, no dump round-trip
require"tracegc".start()
report"gc.lua"
local f = assert(myloadfile('gc.lua'))
f()
ddofile('db.lua')
assert(ddofile('calls.lua') == deep and deep)
_G.deep = nil
dofile('strings.lua')
dofile('literals.lua')
ddofile('tpack.lua')
assert(ddofile('attrib.lua') == 27)
ddofile('gengc.lua')
assert(ddofile('locals.lua') == 5)
print("SUITE-PREFIX PASS")
""")

out = sys.argv[1] if len(sys.argv) > 1 else "tests/suite-prefix-bundle.lua"
with open(out, "w") as fh:
    fh.write("\n".join(parts))
print(f"wrote {out}")
